server:
  port: 8080
#  servlet:
#    context-path: /api

logging:
  level:
    root: info
    com.lrm: debug
  file: logs/debug.log


#declare a variable
#book:
#  name: Intro to java by ${book.author}
#  author: Yubo
#  isbn: ${random.uuid}
#  description: This is a great book.
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 572641339
  jpa:
    hibernate:
      ddl-auto: update
    #      ddl-auto: create
    show-spl: true

